# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY python2_consumer.py /app/

# Install any needed packages specified in requirements.txt
RUN pip install confluent-kafka
RUN pip install kafka-python


# Run python2_consumer.py when the container launches
CMD ["python", "python2_consumer.py"]
