# Use an official Spark base image
FROM bitnami/spark:3.5.0
ENV SPARK_SUBMIT_OPTIONS="--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0"

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY spark_app.py /app/

# Install any needed packages specified in requirements.txt
RUN pip install pymongo

# Run spark_app.py when the container launches
CMD ["spark-submit", "--master", "local", "spark_app.py"]
